### ISSUE TITLE
Checkstyle Header check does not work as expected

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/static-code-analysis#3]
On almost all (openHAB2) files, I see the checkstyle error:

```
Line does not match expected header line of ' * All rights reserved. This program and the accompanying materials'.
```

although the files have a correct license header, see e.g. https://openhab.ci.cloudbees.com/view/Pull%20Request%20Builds/job/openHAB2-CodeAnalysis/lastSuccessfulBuild/artifact/addons/binding/org.openhab.binding.feed/target/code-analysis/report.html.

**Comment by svilenvul** [comment]
I can apply a temporary fix now, but I prefer to make a refactoring of the tool too to avoid similar issues later. The check doesn't work as expected because it is using the ESH license header as a correct header.

The problem is that [the ruleset files for PMD, Checkstyle and FindBugs](https://github.com/openhab/static-code-analysis/tree/master/src/main/resources/rulesets) (where the correct license header is set) are part of the plugin itself. They should be individual for each repository, as each repository might have different configuration for the same check (as in this case the HeaderCheck uses different headers).

I am just wondering if the [configurations of the individual plugins](https://github.com/openhab/static-code-analysis/tree/master/src/main/resources/configuration) should be moved out of the plugin too ...

**Comment by svilenvul** [comment]
Solved by #6.

Opened #7 to continue the discussion that started here.

**Comment by kaikreuzer** [comment]
#6 unfortunately does not solve this. Would there be a chance to relax the check a bit to only check for the existence of certain strings like e.g. "made available under the terms of the Eclipse Public License v1.0" and "by the respective copyright holders"?

**Comment by svilenvul** [comment]
I am a little bit surprised, because I tested it locally and it seems to be working. 

Yes, I can configured the check to skip all lines expect these two.

**Comment by kaikreuzer** [comment]
> I am a little bit surprised, because I tested it locally and it seems to be working.

I have just triggered https://openhab.ci.cloudbees.com/job/openHAB2-CodeAnalysis/5/ - let's wait what comes out of this. This should be our official reference to see whether it is working or not.

In #6 you seem to check for "Copyright (c) 2010-year" - how could that possibly work correctly?

> to skip all lines expect these two.

Note that these are two strings only, not complete lines. But if it works with the full header check, this is also fine by me - it is probably the best to make sure that the license headers are up-to-date and fully correct.

**Comment by svilenvul** [comment]
> In #6 you seem to check for "Copyright (c) 2010-year" - how could that possibly work correctly?

This line is ignored in the current configuration. As it might be important for consistency I will unignore it.

**Comment by svilenvul** [comment]
>I have just triggered https://openhab.ci.cloudbees.com/job/openHAB2-CodeAnalysis/5/ - let's wait what comes out of this. This should be our official reference to see whether it is working or not.

Unfortunately the build has failed and no artifacts are attached.

**Comment by kaikreuzer** [comment]
I'll try once more. Don't know, why it keeps failing to download the jars...

**Comment by kaikreuzer** [comment]
Ok, you have won, it actually all looks good: https://openhab.ci.cloudbees.com/job/openHAB2-CodeAnalysis/lastSuccessfulBuild/artifact/target/summary_report.html!

**Comment by svilenvul** [comment]
btw, should an incorrect header fail the build ?

**Comment by kaikreuzer** [comment]
no, because we have some situations where we have 3rd party source code in the repo, which can potentially have a different license header.
